workflows:
  android-release:
    name: Android Release
    environment:
      flutter: stable
    scripts:
      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Check for outdated packages
        script: flutter pub outdated
      - name: Upgrade packages
        script: flutter pub upgrade
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa