// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnn6Y-zN_mXIVRsw2jafvUm15rWNw030g',
    appId: '1:134095382214:web:49547658828148b5b199c7',
    messagingSenderId: '134095382214',
    projectId: 'demprojo',
    authDomain: 'demprojo.firebaseapp.com',
    databaseURL: 'https://demprojo-default-rtdb.firebaseio.com',
    storageBucket: 'demprojo.firebasestorage.app',
    measurementId: 'G-HWNL72FM87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlTs_hABznh_eHYfmxPDOPh8itbU1CWvY',
    appId: '1:134095382214:android:035f983db91c813bb199c7',
    messagingSenderId: '134095382214',
    projectId: 'demprojo',
    databaseURL: 'https://demprojo-default-rtdb.firebaseio.com',
    storageBucket: 'demprojo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyNwv0O4qAwOezqT17lGmEg_gKpcui3Uc',
    appId: '1:134095382214:ios:b64ef23ea7bbced1b199c7',
    messagingSenderId: '134095382214',
    projectId: 'demprojo',
    databaseURL: 'https://demprojo-default-rtdb.firebaseio.com',
    storageBucket: 'demprojo.firebasestorage.app',
    iosClientId: '134095382214-pkrp2crk6fnuj0n17dtj2orgn8n1o05o.apps.googleusercontent.com',
    iosBundleId: 'com.wilson.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyNwv0O4qAwOezqT17lGmEg_gKpcui3Uc',
    appId: '1:134095382214:ios:b44876f4e78c9b63b199c7',
    messagingSenderId: '134095382214',
    projectId: 'demprojo',
    databaseURL: 'https://demprojo-default-rtdb.firebaseio.com',
    storageBucket: 'demprojo.firebasestorage.app',
    iosClientId: '134095382214-c7suc7g98dg4lc63tdlilfo7nkav6env.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjpv5daHIIg46-_JW6C-9W88NN-bULUGg',
    appId: '1:134095382214:web:d2285501b90e28c0b199c7',
    messagingSenderId: '134095382214',
    projectId: 'demprojo',
    authDomain: 'demprojo.firebaseapp.com',
    databaseURL: 'https://demprojo-default-rtdb.firebaseio.com',
    storageBucket: 'demprojo.firebasestorage.app',
    measurementId: 'G-9T75SX7G7L',
  );
}
